### ISSUE TITLE
Update F3 to 3-3-0 ?

### ISSUE THREAD

**Issue by paullee18** [Poulern/F3_PA#23]
Ignore this if the core F3 files are actually all updated (Just going off the repo description).

Should we update the framework to include all the changes from 3-3-0? Seems to be mostly fixes and performance optimizations.

-Khaki

**Comment by Poulern** [comment]
It should already be up to date. Blaffer and I sort of have areas of responsibility(more like i dont get to touch shit and break it :P ). F3 isn't in full development anymore, just maintenance for the most part. Which is a shame cause i'd really like the wave based respawn they've been teasing me for over a year now. most of the development are done in community based F3 derivatives like our own.

**Comment by captainblaffer** [comment]
As long as our current version of the framework works, and there are no complaints, there is no need to try and break it

**Comment by paullee18** [comment]
Okay, sounds good to me!
