### ISSUE TITLE
Add DMR class across all loadouts / framework

### ISSUE THREAD

**Issue by cptnnick** [Poulern/F3_PA#3]
- [x] Radio integration
- [ ] Vanilla gear script integration
- [ ] Mod gear script integration
- [ ] anything else

**Comment by Poulern** [comment]
Desingated marksman? Good idea i was considering doing it for my Us platoon, but wasn't really that hot on it.

**Comment by cptnnick** [comment]
I already integrated it into the TFR component, I also coined the idea in
the F3 chat and people were supportive of the idea. So it's already
possible to add them yourself atm, and it'll likely become official soon
ish as well.

**Comment by Poulern** [comment]
Closing this for now as no longer worked on.
