### ISSUE TITLE
What do with radios while waiting for newest F3.

### ISSUE THREAD

**Issue by Poulern** [Poulern/F3_PA#4]
While we can easily utilize the modules, I'm a bit afraid of the new mission makers, as they will most likely have the whole 31-39 thing happen and people bitching in the AAR. We could update the mission.sqm to include these preplaced, but I'm not sure if thats a good idea at all. 

Stick with what we got for now i guess?

**Comment by cptnnick** [comment]
Rewriting the TFR component is something I want to do, but it will take a
while still.
